<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>financial_accounting_calculate_calculator_finance_consultation_calculation_report_tax_icon_233530.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="financial_accounting_calculate_calculator_finance_consultation_calculation_report_tax_icon_233530.ico" />
  </ItemGroup>

</Project>